import { FormEvent, useState } from 'react';
import { createLog } from '../../services/logs.api';
import { DailyLog, DailyLogInput, SocialInteractionFrequency } from '../../types/daily-log';
const today = new Date().toISOString().slice(0, 10);
const initial = (): DailyLogInput => ({ logDate: today, moodRating: 5, anxietyLevel: 5, stressLevel: 5, sleepHours: 7, sleepQuality: 3, sleepDisturbances: 0, physicalActivityType: null, physicalActivityMinutes: 0, socialInteractionFrequency: 'moderate', depressionSymptomsPresent: false, depressionSeverity: null, anxietySymptomsPresent: false, anxietySymptomSeverity: null, notes: null });
const Range = ({ label, value, onChange, min = 1, max = 10, hint }: { label: string; value: number; onChange: (value: number) => void; min?: number; max?: number; hint?: string }) => <label className="block"><span className="flex justify-between text-sm font-medium text-ink">{label}<span className="rounded-full bg-mist px-2 font-mono text-xs leading-6 text-moss" title={hint}>{value}/{max}</span></span><input className="mt-2 w-full accent-moss" type="range" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))}/></label>;
export const DailyLogForm = ({ onCreated }: { onCreated: (log: DailyLog) => void }) => {
  const [form, setForm] = useState(initial); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  function update<K extends keyof DailyLogInput>(key: K, value: DailyLogInput[K]): void { setForm((current) => ({ ...current, [key]: value })); }
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(null); try { const { data } = await createLog(form); onCreated(data); setMessage('Tu registro está guardado. Gracias por hacer espacio para ti.'); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'No fue posible guardar el registro.'); } finally { setSaving(false); } };
  const symptom = (presentKey: 'depressionSymptomsPresent' | 'anxietySymptomsPresent', severityKey: 'depressionSeverity' | 'anxietySymptomSeverity', label: string) => <div className="rounded-xl bg-mist p-3"><label className="flex cursor-pointer items-center justify-between gap-4 text-sm font-medium text-ink"><span>{label}</span><input type="checkbox" checked={form[presentKey]} onChange={(event) => { update(presentKey, event.target.checked); update(severityKey, event.target.checked ? 1 : null); }} /></label>{form[presentKey] && <div className="mt-3"><Range label="Intensidad" value={form[severityKey] ?? 1} onChange={(value) => update(severityKey, value)} /></div>}</div>;
  return <form onSubmit={submit} className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><Range label="¿Cómo está tu ánimo hoy?" value={form.moodRating} onChange={(value) => update('moodRating', value)} hint="1: muy bajo · 10: muy alto"/><Range label="Nivel de ansiedad" value={form.anxietyLevel} onChange={(value) => update('anxietyLevel', value)} hint="1: muy bajo · 10: muy alto"/><Range label="Nivel de estrés" value={form.stressLevel} onChange={(value) => update('stressLevel', value)} /></div><div className="border-t border-sage/20 pt-5"><p className="mb-4 font-serif text-xl text-ink">Descanso y movimiento</p><div className="grid gap-4 sm:grid-cols-3"><label className="field">Horas de sueño<input type="number" step="0.5" min="0" max="24" value={form.sleepHours} onChange={(event) => update('sleepHours', Number(event.target.value))}/></label><Range label="Calidad del sueño" value={form.sleepQuality} max={5} onChange={(value) => update('sleepQuality', value)} /><label className="field">Despertares<input type="number" min="0" max="20" value={form.sleepDisturbances} onChange={(event) => update('sleepDisturbances', Number(event.target.value))}/></label><label className="field">Actividad física<input placeholder="Ej. caminar" value={form.physicalActivityType ?? ''} onChange={(event) => update('physicalActivityType', event.target.value || null)}/></label><label className="field">Minutos de actividad<input type="number" min="0" max="1440" value={form.physicalActivityMinutes} onChange={(event) => update('physicalActivityMinutes', Number(event.target.value))}/></label><label className="field">Interacciones sociales<select value={form.socialInteractionFrequency} onChange={(event) => update('socialInteractionFrequency', event.target.value as SocialInteractionFrequency)}><option value="none">Ninguna</option><option value="low">Pocas</option><option value="moderate">Moderadas</option><option value="high">Muchas</option></select></label></div></div><div className="border-t border-sage/20 pt-5"><p className="mb-3 font-serif text-xl text-ink">Síntomas, si deseas registrarlos</p><div className="grid gap-3 sm:grid-cols-2">{symptom('depressionSymptomsPresent', 'depressionSeverity', 'Síntomas de depresión')}{symptom('anxietySymptomsPresent', 'anxietySymptomSeverity', 'Síntomas de ansiedad')}</div><label className="field mt-4">Una nota para ti<textarea rows={3} placeholder="¿Hay algo que quieras recordar de hoy?" value={form.notes ?? ''} onChange={(event) => update('notes', event.target.value || null)}/></label></div>{message && <p role="status" className="rounded-xl bg-lavender/50 px-4 py-3 text-sm text-ink">{message}</p>}<button className="w-full rounded-xl bg-moss px-5 py-3 font-semibold text-white transition hover:bg-ink focus:outline-none focus:ring-4 focus:ring-sage/30 disabled:opacity-60" disabled={saving}>{saving ? 'Guardando…' : 'Guardar mi registro de hoy'}</button></form>;
};
